import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

type SinglePostPageProps = {
  id: string;
}

const SinglePostPage: NextPage<SinglePostPageProps> = ({ id }: SinglePostPageProps) => {
  const { data, isLoading } = api.posts.get.useQuery({ id: id });
  const { data: commentsData } = api.comments.getCommentsForPostId.useQuery({ postId: id });

  if (!data) {
    return <div>Post not found</div>;
  }

  return (
    <>
      <Head>
        <title>{data?.post.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <CreateCommentWizard postId={id} />
            {isLoading ? <div>Loading...</div> :
              <PostView {...data} />
            }
          {
            commentsData ?
              commentsData.map((comment) => (
                <CommentView {...comment} key={comment.comment.id} />
              ))
              : <div>No comments</div>
          }
        </div>
      </div>
    </>
  );
};

export default SinglePostPage;

import { createProxySSGHelpers } from "@trpc/react-query/ssg";
import { appRouter } from "~/server/api/root";
import { prisma } from "~/server/db";
import superjson from "superjson";
import { CreateCommentWizard } from "~/components/CreateCommentWizard";
import { CommentView } from "~/components/commentview";
import { PostView } from "~/components/postview";

export const getStaticProps: GetStaticProps = async (context) => {
  const ssg = createProxySSGHelpers({
    router: appRouter,
    ctx: { prisma, userId: null },
    transformer: superjson,
  });

  const slug = context.params?.slug;

  if (typeof slug !== "string") throw new Error("Slug is not a string");

  await ssg.posts.get.prefetch({ id: slug });
  await ssg.comments.getCommentsForPostId.prefetch({ postId: slug });

  return {
    props: {
      id: slug,
      trpcState: ssg.dehydrate(),
    }
  };
}

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};
